# Generated by Django 5.1.4 on 2026-05-24 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('airport_name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=80)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=120)),
                ('scope_category', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3'), ('unknown', 'Unknown')], max_length=20)),
                ('unit', models.CharField(max_length=32)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source_note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('normalized_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('suspicious_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_key', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=120)),
                ('scope_category', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3'), ('unknown', 'Unknown')], max_length=20)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=32)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=32)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('location_code', models.CharField(blank=True, max_length=80)),
                ('location_name', models.CharField(blank=True, max_length=160)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('suspicious', 'Suspicious'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending_review', max_length=20)),
                ('confidence_score', models.PositiveSmallIntegerField(default=80)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='core.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.activityrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='importbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='core.organization'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('import', 'Import'), ('parse', 'Parse'), ('edit', 'Edit'), ('approve', 'Approve'), ('reject', 'Reject'), ('lock', 'Lock')], max_length=20)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.activityrecord')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_key', models.CharField(blank=True, max_length=255)),
                ('row_number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('parser_status', models.CharField(choices=[('normalized', 'Normalized'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('parser_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_record', to='core.rawrecord'),
        ),
        migrations.CreateModel(
            name='ReviewFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.activityrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP fuel/procurement CSV'), ('utility', 'Utility Green Button XML'), ('travel', 'Concur-style travel JSON')], max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('ingestion_mechanism', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'source_type')},
            },
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='core.sourcesystem'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='core.sourcesystem'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_records', to='core.sourcesystem'),
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_unit', models.CharField(max_length=32)),
                ('target_unit', models.CharField(max_length=32)),
                ('multiplier', models.DecimalField(decimal_places=8, max_digits=16)),
                ('activity_hint', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'unique_together': {('source_unit', 'target_unit', 'activity_hint')},
            },
        ),
        migrations.CreateModel(
            name='MeterLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=80)),
                ('facility_name', models.CharField(max_length=160)),
                ('tariff', models.CharField(blank=True, max_length=120)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'meter_id')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('auditor', 'Auditor')], default='analyst', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=40)),
                ('plant_name', models.CharField(max_length=160)),
                ('country', models.CharField(max_length=80)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'plant_code')},
            },
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['organization', 'source_row_key'], name='core_rawrec_organiz_3ae238_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'status', 'scope_category'], name='core_activi_organiz_9ce456_idx'),
        ),
    ]
